cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('update-quantity/', views.update_quantity, name='update_quantity'),
    path('remove-item/', views.remove_item, name='remove_item'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Product
from .cart import Cart
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST


# Create your views here.
@require_POST
def add_to_cart(request, pk):
     product = get_object_or_404(Product, id=pk)
     cart = Cart(request)
     cart.add(product)
     context = {
         'total_items': len(cart)
     }
     return JsonResponse(context)


def cart_detail(request):
    return render(request, "cart/cart_detail.html")


@require_POST
def update_quantity(request):
    product_id = request.POST['id']
    product = get_object_or_404(Product, id=product_id)
    action = request.POST['action']
    cart = Cart(request)
    try:
         if action == 'increase':
              cart.add(product)
         else:
              cart.decrease(product)
         return JsonResponse({
              'total_items': len(cart)
         })
    except:
         return JsonResponse({
              'error': 'request is Invalid'
         })
    

def remove_item(request):
    product_id = request.POST.get('itemID')
    cart = Cart(request)
    cart.remove(product_id)
    return JsonResponse(
         {'total-items': len(cart)}
    )

cart/templates/cart/cart_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block title %} shopping cart {% endblock %}
{% block content %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('.increase-item').click(function(){
            updateQuantity($(this).closest('.items').data('product-id'), 'increase');
        })

        $('.decrease-item').click(function(){
            updateQuantity($(this).closest('.items').data('product-id'), 'decrease');
        })
		
        $('.remove-item').click(function(){
            var itemID = $(this).closest('.items').data('product-id');
            var removeBtn = $(this);
            $.ajax({
                type: 'POST',
                url: '{% url "cart:remove_item" %}',
                data: {'itemID': itemID, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(response){
                    $('#site-header').load('/partials/header/');
                    $('#total-items').text(response.total_items);
                    $(removeBtn).closest('.items').remove();
                }
            })
        })

		function updateQuantity(id, action){
			$.ajax({
				type: 'POST',
                url: '{% url "cart:update_quantity" %}',
                data: {'id': id, 'action': action, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data){
                    $("#total-items").text(data.total_items);
                    },
	            })
            }
        })
</script>

</body>
{% endblock %}