account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('phone-login/', views.phone_login, name='phone_login'),
    path('register/', views.register, name="register"),
    path('verify-code/', views.verify_code, name='verify_code'),
    path('logout/', views.user_logout, name='user_logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('update-quantity/', views.update_quantity, name='update_quantity'),
    path('remove-item/', views.remove_item, name='remove_item'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('partials/<str:name>/', views.partials, name='partials'),
    path('products/', views.products, name='products'),
    path('products/<slug:category_slug>/', views.products, name='products_by_category'),
    path('product/<int:id>/<str:slug>/', views.product, name='product'),
    path('like/<int:id>/', views.like_view, name='like_view'),
    path('search/', views.search, name='search'),
]

myshop/templates/partials/header.html
<header>
  <style>  
  .cart-icon {
  position: relative;
  font-size: 24px;
  text-decoration: none;
}

#total-items {
  position: absolute;
  top: -6px;
  right: -8px;

  background: red;
  color: white;

  font-size: 11px;
  font-weight: bold;

  width: 18px;
  height: 18px;
  border-radius: 50%;

  display: flex;
  align-items: center;
  justify-content: center;

  line-height: 1;
}
</style>

  <div class="header-container">

    <!-- لوگو -->
    <a href="/" class="logo">جواهرات سَرای زَر</a>

    <!-- جستجو -->
    <div class="search-box">
      <input type="text" placeholder="جستجوی گردنبند، انگشتر، دستبند طلایی..." name="query" class="search-input"/>
	  <div class="search-results"></div>
    </div>

    <!-- آیکون‌ها -->
    <div class="right-section">

      <!-- سبد خرید / فروشگاه -->
      <a href="{% url 'cart:cart_detail' %}" class="icon-btn cart-icon" title="سبد خرید">
      🛍️
        <span id="total-itmes">{{ cart|length }}</span>
      </a>

      <!-- پروفایل کاربر -->
      {% if user.is_authenticated %}
      <a href="#" class="icon-btn" title="حساب کاربری">
        <!-- اگر عکس داشتید از این استفاده کنید: -->
        <!-- <img src="user-avatar.jpg" class="profile-img" alt="profile"> -->
        <!-- در غیر این صورت آیکون ساده: -->
        👤
      </a>
      {% else %}
      <a href="{% url 'account:phone_login' %}" class="icon-btn" title="ورود به حساب کاربری">
        ورود
      </a>
      {% endif %}

    </div>

  </div>

<script>
let searchInput = document.querySelector('.search-input');
let searchItems = document.querySelector('.search-results');
searchInput.addEventListener('input', function(){
	searchItems.innerHTML = '';
	fetch('{% url "shop:search" %}?query=' + this.value, {
		  method: 'GET',
		  headers: {"X-CSRFToken": '{{ csrf_token }}'}
		  }).then(function(res){
		      return res.json()
		  }).then(data => {
	        // searchItems.append(data)
	      data.searched_res.forEach(element => {
	      const a = document.createElement("a");
				a.href = 'product/' + element.id + '/' + element.slug + '/'
				a.textContent = element.name + " سرچ شده";
	  			searchItems.appendChild(a);
	        });
	      });
		})
</script>

</header>

</head>