cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('update-quantity/', views.update_quantity, name='update_quantity'),
    path('remove-item/', views.remove_item, name='remove_item'),

]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('order.urls', namespace='order')),
    path('api/', include('api.urls', namespace='api'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path('partials/<str:name>/', views.partials, name='partials'),
    path('products/', views.products, name='products'),
    path('products/<slug:category_slug>/', views.products, name='products_by_category'),
    path('product/<int:id>/<str:slug>/', views.product, name='product'),
    path('like/<int:id>/', views.like_view, name='like_view'),
    path('search/', views.search, name='search'),
]

shop/models.py
from django.db import models
# from django.core.validators import MinValueValidator, MaxValueValidator
# from account.models import ShopUser
import os
from django.shortcuts import reverse
# from decimal import Decimal
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    
    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    description = models.CharField(max_length=2500)
    inventory = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)
    discount = models.FloatField(default=0)
    weight = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField('account.ShopUser', related_name='likes', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def new_price(self):
        discount_price = self.price - (self.price * self.discount)
        return discount_price
    
    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"
    
    def get_absolute_url(self):
        return reverse('shop:product', kwargs={'id': self.id, 'slug': self.slug})


class ProductFeatures(models.Model):
    product = models.ForeignKey(Product, related_name="features", on_delete=models.CASCADE, null=True, blank=True)
    key = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.key} : {self.value}"


class Image(models.Model):
    prudoct = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image_file = models.ImageField(upload_to="images/%Y/")
    title = models.CharField(max_length=250, null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.title if self.title else os.path.basename(self.image_file.name)

shop/forms.py
from django import forms

shop/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from cart.cart import Cart
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# import json

# Create your views here.

# partials
def partials(request, name):
    return render(request, f"partials/{name}.html/")


def products(request, category_slug=None):
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = categories.get(slug=category_slug)
        products = products.filter(category=category)
    
    context = {'categories': categories, 'products': products}
    return render(request, "shop/products.html", context)


def product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    context = {
        'product': product
    }
    return render(request, "shop/product.html", context)


def search(request):
    query = request.GET.get('query')
    if query:
        searched_res = Product.objects.filter(Q(name__icontains=query)).values('id', 'slug', 'name')
        return JsonResponse({'searched_res': list(searched_res)})


@login_required
@require_POST
def like_view(request, id):
    product = get_object_or_404(Product, id=id)
    if request.user in product.liked_by.all():
        print('hi')
        product.liked_by.remove(request.user)
        liked = False
    else:
        print('hi')
        product.liked_by.add(request.user)
        liked = True

    response_data = {'liked': liked}
    return JsonResponse(response_data)

shop/templates/shop/product.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block title %} {{ product.name }} {% endblock %}
{% block head %}
{% endblock %}
{% block content %}

<section class="product-section">
  <div class="product-container">

    <div class="product-image">
      <img src="{{ product.images.first.image_file.url }}" alt="{{ product.name }}">
    </div>

    <div class="product-info">
      <div>
        <h2>گردنبند طلای ۱۸ عیار طرح کلاسیک</h2>
        <p>
          گردنبند طلای ۱۸ عیار با طراحی لوکس و ظریف، مناسب استفاده روزمره و مجالس رسمی.
          ساخته شده با بالاترین کیفیت ساخت و درخشندگی ماندگار.
        </p>
        <div class="price">{{product.new_price}}</div>
      </div>

      <button class="buy-btn" data-csrf="{{csrf_token}}">افزودن به سبد خرید</button>

      <button class="like-btn">
        {% if request.user in product.liked_by.all %}
            ♡
        {% else %}
            ❤️
        {% endif %}
      </button>
    </div>

  </div>
</section>

<script>
    let likeBtn = document.querySelector('.like-btn');
    likeBtn.addEventListener('click', function(){
        fetch('{% url "shop:like_view" product.id %}', {
            method: 'POST',
            headers: {"X-CSRFToken": '{{ csrf_token }}', "Content-Type": "application/json"},
        }).then(data => {return data.json()})
        .then(function(data){
            if (data.liked){
                likeBtn.innerHTML = '♡'
            } else {
                likeBtn.innerHTML = '❤️'
            }
        })
    })

    let totalItems = document.getElementById('total-itmes');
    let buyBtn = document.querySelector('.buy-btn');
    buyBtn.addEventListener('click', function(){
      fetch('{% url "cart:add_to_cart" product.id %}', {
        method: 'POST',
        headers: {"X-CSRFToken": buyBtn.getAttribute('data-csrf'), "Content-Type": "application/json"},
      })
      .then(data => {return data.json()})
      .then(res => {totalItems.innerHTML = res.total_items})
    })
</script>

{% endblock %}

shop/templates/shop/products.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block title %} products {% endblock %}
{% block head %}
{% endblock %}
{% block content %}

<main>
    <h1>محصولات</h1>
    <div class="categories">
        <a class="category-btn active" 
           data-category="all" 
           href="{% url 'shop:products' %}">همه</a>

        {% for cat in categories %}
            <a class="category-btn" 
               href="{% url 'shop:products_by_category' cat.slug %}">
                {{ cat.name }}
            </a>
        {% endfor %}
    </div>

  <div class="products-grid">
    {% for product in products %}
    <!-- نمونه محصول زنانه -->
    <div class="product-card" data-category="{{ product.category }}">
      <div class="product-img-container">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-img">
      </div>

      <div class="product-info">
        <a href="{% url 'shop:product' product.id product.slug %}"><h3 class="product-title">{{ product.name }}</h3></a>
        <div class="product-price">{{ product.price }} تومان</div>
        <button class="add-to-cart">افزودن به سبد</button>
      </div>
    </div>
    {%endfor%}

  </div>
</main>

{% endblock %}